apache/rocketmq-streams

rocketmq-streams-channel-db/pom.xml, rocketmq-streams-channel-http/pom.xml, rocketmq-streams-clients/pom.xml, rocketmq-streams-commons/pom.xml, rocketmq-streams-configurable/pom.xml, rocketmq-streams-db-operator/pom.xml, rocketmq-streams-dbinit/pom.xml, rocketmq-streams-filter/pom.xml, rocketmq-streams-lease/pom.xml, rocketmq-streams-schedule/pom.xml, rocketmq-streams-script/pom.xml, rocketmq-streams-serviceloader/pom.xml, rocketmq-streams-transport-minio/pom.xml, rocketmq-streams-window/pom.xml
fulfil some pom.xml apache license
=> fulfil apache license

rocketmq-streams-transport-minio/src/test/java/org/apache/rocketmq/streams/configuable/model/DataTpyeTest.java
=> add testcase

README.md
added english descriptions of read.me
=> added english descriptions of read.me

README.md, pom.xml
Exclude CI files in apache rat check
=> [ISSUE #33]Exclude CI files in apache rat check

rocketmq-streams-commons/src/main/java/org/apache/rocketmq/streams/common/functions/FlatMapFunction.java
=> add license header

pom.xml, rocketmq-streams-channel-rocketmq/src/main/java/org/apache/rocketmq/streams/sink/RocketMQSink.java, rocketmq-streams-clients/src/main/java/org/apache/rocketmq/streams/client/transform/DataStream.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/windows/AbstractWindowTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/windows/MultiSplitTest.java, rocketmq-streams-clients/src/test/resources/window_msg_10, rocketmq-streams-clients/src/test/resources/window_msg_100, rocketmq-streams-clients/src/test/resources/window_msg_1000, rocketmq-streams-clients/src/test/resources/window_msg_10000, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/shuffle/AbstractSystemChannel.java
Polish rocketmq topic create process and rocketmq settings
=> [ISSUE #65]Polish RocketMQ topic create process and sink settings

rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/operator/AbstractShuffleWindow.java, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/shuffle/ShuffleChannel.java
fix(window) fix queuelist null pointer exception
=> fix(window) fix queuelist null pointer exception

rocketmq-streams-commons/src/main/java/org/apache/rocketmq/streams/common/batchsystem/BatchFinishMessage.java, rocketmq-streams-examples/src/main/java/org/apache/rocketmq/streams/examples/filesource/FileSourceExample.java
=> [ISSUE #97]Fix file source example

rocketmq-streams-channel-rocketmq/src/main/java/org/apache/rocketmq/streams/source/RocketMQSource.java
fix example: RocketMQSourceExample1,make RocketMQSourceExample1 run success.
=> [ISSUE #101]Fix example RocketMQSourceExample1

rocketmq-streams-clients/src/main/java/org/apache/rocketmq/streams/client/DataStreamAction.java, rocketmq-streams-clients/src/main/java/org/apache/rocketmq/streams/client/source/DataStreamSource.java
1. fix npe in two streams case. set otherPipelineBuilders.
2. init otherPipelines at first to avoid miss mainPipeline's following stages after windowStage.
=> Fix npe two streams & fix joinwindow's production donot be conducted by mainpipeline's following stages

NOTICE
=> The year should be updated to 2022 in NOTICE file

README-chinese.md
https://github.com/apache/rocketmq-streams/issues/133
=> [ISSUES #133] Add design doc into README-chinese.md

rocketmq-streams-commons/src/main/java/org/apache/rocketmq/streams/common/utils/SQLUtil.java, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/offset/WindowMaxValueProcessor.java, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/operator/impl/SessionOperator.java, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/trigger/WindowTrigger.java
- adjust test code in WindowTrigger in case the window which size unit is minute
- adjust register logic in session window operator
- fix issue of window value can't be delete after fired
=> bugfix list

rocketmq-streams-clients/src/main/java/org/apache/rocketmq/streams/client/transform/JoinStream.java, rocketmq-streams-clients/src/main/java/org/apache/rocketmq/streams/client/transform/OverWindowStream.java, rocketmq-streams-clients/src/main/java/org/apache/rocketmq/streams/client/transform/WindowStream.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/DataStreamTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/JoinTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/RocketMQGroupByTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/SplitTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/UnionTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/WindowTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/example/CountFromFileTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/example/CountSupportEmitTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/example/DimTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/example/JoinTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/source/MqttStreamsTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/windows/AbstractWindowFireModeTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/windows/AbstractWindowTest.java, rocketmq-streams-clients/src/test/java/org/apache/rocketmq/streams/client/windows/ShuffleOverWindowTest.java, rocketmq-streams-examples/src/main/java/org/apache/rocketmq/streams/examples/aggregate/PageDimensionExample.java, rocketmq-streams-examples/src/main/java/org/apache/rocketmq/streams/examples/aggregate/RocketMQWindowExample.java, rocketmq-streams-examples/src/main/java/org/apache/rocketmq/streams/examples/aggregate/UsersDimensionExample.java, rocketmq-streams-examples/src/main/java/org/apache/rocketmq/streams/examples/checkpoint/RemoteCheckpointExample.java, rocketmq-streams-examples/src/main/java/org/apache/rocketmq/streams/examples/join/RocketmqDimJoinExample.java, rocketmq-streams-examples/src/main/java/org/apache/rocketmq/streams/examples/join/RocketmqJoinExample.java, rocketmq-streams-examples/src/main/java/org/apache/rocketmq/streams/examples/mutilconsumer/MultiStreamsExample.java, rocketmq-streams-examples/src/main/java/org/apache/rocketmq/streams/examples/source/MqttSourceExample.java, rocketmq-streams-examples/src/main/java/org/apache/rocketmq/streams/examples/source/RocketmqSourceExample4.java
=> [ISSUE #175] Corrects a spelling error in the word "stream"

rocketmq-streams-channel-rocketmq/pom.xml, rocketmq-streams-examples/pom.xml, rocketmq-streams-serviceloader/pom.xml
Add dependency in serviceLoad module
=> Add dependency in serviceLoad module

rocketmq-streams-commons/src/main/java/org/apache/rocketmq/streams/common/checkpoint/CheckPointStorageFactory.java, rocketmq-streams-commons/src/main/java/org/apache/rocketmq/streams/common/utils/ReflectUtil.java
close [ISSUE #202](https://github.com/apache/rocketmq-streams/issues/202)
=> [ISSUE #202] adapt jdk11

rocketmq-streams-commons/src/main/java/org/apache/rocketmq/streams/common/channel/sinkcache/impl/AbstractMultiSplitMessageCache.java, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/fire/EventTimeManager.java, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/operator/impl/SessionOperator.java, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/operator/join/JoinWindow.java, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/storage/IStorage.java, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/storage/RocksdbIterator.java, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/storage/rocketmq/DefaultStorage.java, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/storage/rocksdb/RocksdbStorage.java, rocketmq-streams-window/src/main/java/org/apache/rocketmq/streams/window/trigger/WindowTrigger.java
close https://github.com/apache/rocketmq-streams/issues/210
=> [ISSUE #210]support session and hop window

rocketmq-streams-channel-rocketmq/src/main/java/org/apache/rocketmq/streams/sink/RocketMQSink.java, rocketmq-streams-commons/src/main/java/org/apache/rocketmq/streams/common/component/ComponentCreator.java, rocketmq-streams-script/src/main/java/org/apache/rocketmq/streams/script/service/udf/UDFScript.java
close https://github.com/apache/rocketmq-streams/issues/213
=> [ISSUE #213]fix(custom function) support utf

rocketmq-streams-channel-rocketmq/src/main/java/org/apache/rocketmq/streams/schema/AvroSchemaWrapper.java, rocketmq-streams-channel-rocketmq/src/main/java/org/apache/rocketmq/streams/schema/CustomSchemaWrapper.java, rocketmq-streams-channel-rocketmq/src/main/java/org/apache/rocketmq/streams/schema/JsonSchemaWrapper.java, rocketmq-streams-channel-rocketmq/src/main/java/org/apache/rocketmq/streams/schema/SchemaConfig.java, rocketmq-streams-channel-rocketmq/src/main/java/org/apache/rocketmq/streams/schema/SchemaWrapperFactory.java, rocketmq-streams-examples/src/main/java/org/apache/rocketmq/streams/examples/schema/CustomeDeserializerExample.java, rocketmq-streams-examples/src/main/java/org/apache/rocketmq/streams/examples/schema/DataDeserializer.java
The customized deserializer should implement the interface `org.apache.rocketmq.schema.registry.client.serde.Deserializer`
=> support customized deserializer for dataStream from RocketMQ

README.md
=> [ISSUE #234]Add quick start

core/src/main/java/org/apache/rocketmq/streams/core/common/Constant.java, core/src/main/java/org/apache/rocketmq/streams/core/running/WorkerThread.java, core/src/main/java/org/apache/rocketmq/streams/core/state/RocketMQStore.java, core/src/main/java/org/apache/rocketmq/streams/core/util/RocketMQUtil.java
1. add log when workerThread start;
2. keep state topic consistent with source topic(shuffle topic or user source topic)
3. modify the way create normal topic.
close #255
=> [ISSUE #255] keep state topic consistent with source topic

core/src/main/java/org/apache/rocketmq/streams/core/rstream/RStream.java, core/src/main/java/org/apache/rocketmq/streams/core/rstream/RStreamImpl.java
=> [ISSUE #268]modify the return type of flatmap
